/**
 * @file Version.h
 * @brief Version information for LSM6DS3TR.
 *
 * This file is AUTO-GENERATED by scripts/generate_version.py from library.json.
 * DO NOT EDIT MANUALLY. Update version metadata via library.json or
 * scripts/generate_version.py bump/set commands.
 */

#pragma once

#include <stdint.h>

/// @brief Semantic version string override used by generated version constants.
#ifndef LSM6DS3TR_VERSION_STRING
#define LSM6DS3TR_VERSION_STRING "2.0.1"
#endif

/// @brief Build-date override; defaults to the compiler date.
#ifndef LSM6DS3TR_BUILD_DATE
#define LSM6DS3TR_BUILD_DATE __DATE__
#endif

/// @brief Build-time override; defaults to the compiler time.
#ifndef LSM6DS3TR_BUILD_TIME
#define LSM6DS3TR_BUILD_TIME __TIME__
#endif

/// @brief Combined build timestamp override.
#ifndef LSM6DS3TR_BUILD_TIMESTAMP
#define LSM6DS3TR_BUILD_TIMESTAMP LSM6DS3TR_BUILD_DATE " " LSM6DS3TR_BUILD_TIME
#endif

/// @brief Source revision override injected by supported build tooling.
#ifndef LSM6DS3TR_GIT_COMMIT
#define LSM6DS3TR_GIT_COMMIT "unknown"
#endif

/// @brief Source-tree state override injected by supported build tooling.
#ifndef LSM6DS3TR_GIT_STATUS
#define LSM6DS3TR_GIT_STATUS "unknown"
#endif

/// @brief Complete version/build identity override.
#ifndef LSM6DS3TR_VERSION_FULL
#define LSM6DS3TR_VERSION_FULL LSM6DS3TR_VERSION_STRING " (" LSM6DS3TR_GIT_COMMIT ", " LSM6DS3TR_BUILD_TIMESTAMP ", " LSM6DS3TR_GIT_STATUS ")"
#endif

namespace LSM6DS3TR {

/// @brief Major version (breaking changes).
static constexpr uint16_t VERSION_MAJOR = 2;

/// @brief Minor version (backward-compatible features).
static constexpr uint16_t VERSION_MINOR = 0;

/// @brief Patch version (backward-compatible fixes).
static constexpr uint16_t VERSION_PATCH = 1;

/// @brief Full semantic version string.
static constexpr const char* VERSION = LSM6DS3TR_VERSION_STRING;

/// @brief Encoded version for numeric comparison: MAJOR*10000 + MINOR*100 + PATCH.
static constexpr uint32_t VERSION_CODE = 20001;

/// @brief Backward-compatible alias used by older repositories.
static constexpr int VERSION_INT = 20001;

/// @brief Build date string.
static constexpr const char* BUILD_DATE = LSM6DS3TR_BUILD_DATE;

/// @brief Build time string.
static constexpr const char* BUILD_TIME = LSM6DS3TR_BUILD_TIME;

/// @brief Build timestamp string.
static constexpr const char* BUILD_TIMESTAMP = LSM6DS3TR_BUILD_TIMESTAMP;

/// @brief Git commit string.
static constexpr const char* GIT_COMMIT = LSM6DS3TR_GIT_COMMIT;

/// @brief Git working tree status string.
static constexpr const char* GIT_STATUS = LSM6DS3TR_GIT_STATUS;

/// @brief Full version string with build metadata.
static constexpr const char* VERSION_FULL = LSM6DS3TR_VERSION_FULL;

}  // namespace LSM6DS3TR
